version: '3'

services:
  server:
    build: ./server
    ports:
      - "80:80"
    volumes:
      - ./server/src:/app/src
    networks:
      - app-network

  client:
    build: ./client
    depends_on:
      - server
    volumes:
      - ./client/src:/app/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
