version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my-db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"    
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  express-server:
    build: ./express-server
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cpp-server
    networks:
      - app-network

  cpp-server:
    build: ./cpp-server
    networks:
      - app-network
  cpp-mysql:
    build: ./cpp-mysql
    depends_on:
      - mysql
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
