version: '3'

services:
  server:
    build: ./server
    ports:
      - "80:80"
    networks:
      - app-network

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
